name = "CNS"
grammar = "cns"
path_suffixes = ["cns"]
line_comments = ["# "]
block_comment = ["/*", "*/"]
autoclose_before = "]})>\" \n\t"
brackets = [
  { start = "{", end = "}", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
]
